/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./js/**/*.js"],
  theme: {
    extend: {
      colors: {
        primary: "#c2652a",
        "on-primary": "#ffffff",
        "primary-container": "#ffdbcb",
        "on-primary-container": "#3d1000",
        secondary: "#755846",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffdcc5",
        "on-secondary-container": "#2a1609",
        tertiary: "#685e43",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#e9dfc0",
        "on-tertiary-container": "#221b06",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#410002",
        background: "#fff8f6",
        "on-background": "#231a14",
        surface: "#fff8f6",
        "on-surface": "#231a14",
        "surface-variant": "#f4ded3",
        "on-surface-variant": "#52443c",
        outline: "#85736a",
        "outline-variant": "#d7c2b6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fcf1ec",
        "surface-container": "#f6ebe6",
        "surface-container-high": "#f1e5e0",
        "surface-container-highest": "#f0ded7",
        "surface-dim": "#e7d7d0",
        "inverse-surface": "#392e27",
        "inverse-primary": "#ffb68f",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.5rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        gutter: "24px",
        "margin-mobile": "16px",
        unit: "4px",
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
